print(" ############################    ")
print(" #                          #    ")
print(" #   Muhammad Shofy Akmal   #    ")
print(" #      2210817210023       #    ")
print(" #                          #    ")
print(" ############################    ")